### ISSUE TITLE
node module error

### ISSUE THREAD

**Issue by tabenius** [rubenafo/trendyways#10]
When using the package as a module with npm and e.g. babel and browserify the requires will not work. Missing ./utils required is the first error.

When using git clone and manual compilation: 
  Package do not compile. Missing uglify-es and browserify packages. Install them before running make.

The example script is wrong. The ma function use the "c" attribute by default.. thus the given parameter must be as below. That way of including the package is also the only way I found that works.

"use strict";
import tw from "./trendyways/dist/trendyways.min.js";

console.log(tw.ma([{"c":1.1}, {"c":2.2}, {"c":3.4}, {"c":2.1}], 2))

Great thanks for your efforts!

**Comment by rubenafo** [comment]
Hi,
Did you try running _npm install_ before make? That will install the dependencies required to build successfully.
The example needs to be updated :)

Thanks for your feedback!

**Comment by rubenafo** [comment]
I just released a fix for the error you reported.
I tried to reproduce the issue regarding "missing utils" without success though, can you provide more details?
