### ISSUE TITLE
Vulnerability from jsdoc

### ISSUE THREAD

**Issue by dawadam** [rubenafo/trendyways#7]
=== npm audit security report ===

│ High          │ Regular Expression Denial of Service
│ Package       │ marked
│ Patched in    │ >=0.3.9
│ Dependency of │ trendyways
│ Path          │ trendyways > jsdoc > marked
│ More info     │ https://nodesecurity.io/advisories/531

**Comment by rubenafo** [comment]
Not relevant for prod code
