### ISSUE TITLE
How do deal with RSI smoothing?

### ISSUE THREAD

**Issue by Swiftnesses** [rubenafo/trendyways#8]
Hello,

Firstly, thank you for the great lib.

I'm trying to match my values to that of TradingView (or as close as!). It's my understanding they use an 'undefined' period and apply smoothing to the first period reading. I'm testing using the 1M timeframe and obviously with a small set of data (let's say 20), I'm seeing values much different from that of TV and exchanges. How would you suggest to workaround this, I was looking to provide a rolling dataset of say, 60 ticks to avoid larger swings, is there a better way?

**Comment by rubenafo** [comment]
Hi,
Not sure I understand your issue completely but the window size cannot be greater than your dataset size, e.g for 20 samples your window size has to be smaller than that.
From TradingView docs, it seems they use 14 as default window size (btw is the default suggested by the algorithm)
