### ISSUE TITLE
ma function crashes when used in Angular

### ISSUE THREAD

**Issue by Episodex** [rubenafo/trendyways#9]
I get `sumWindow is not defined` error in `ma` function when I use it in Angular 2+. Maybe because of some strict setting somewhere. Looks like just adding `let` before `sumWindow` in averages.js line 14 should fix the issue.

Edit: It's also in many other places.

**Comment by rubenafo** [comment]
What version of Angular are you using?

**Comment by Episodex** [comment]
Angular 8.2.4, Angular CLI 8.3.1. 

My guess is that it forces somewhere strict mode and it gives errors when variable is not declared before being assigned. For test I added `let` in several places and the errors were indeed solved, but more errors were coming from deeper and deeper parts of code as not declared variables are in many places there. Maybe it's better to just declare them all to comply with strict mode, unless there is a reason to not do it?

**Comment by rubenafo** [comment]
Just checked the code and I agree all those variables should be declared btw :) Some parts of it are quite all so they probably need a review. 
I review them and publish soon.

Thanks for letting me know!

**Comment by rubenafo** [comment]
Hi, just published a new version with the fix:
https://www.npmjs.com/package/trendyways

Cheers!
